services:
  printmqttify:
    image: printmqttify  #image name
    container_name: printmqttify_container  
    privileged: true
    ports:
      - "631:631"  # Map CUPS web interface port Using 1631 avoids conflict with CUPS running on the host. Use "631:631" if not running CUPS on the host machine.
      - "8080:8080" # Map PrintMQTTify configuration page port
    devices:
      - "/dev/usb/lp0:/dev/usb/lp0"  # Map USB printer This needs to be configured to match your printers USB connection
    environment:
      - MQTT_BROKER=192.168.0.71  # Replace with actual MQTT broker IP. If using the Mosquitto add-on in Home Assistant this is probably your Home Assistant IP
      - MQTT_USERNAME=mqtt-username 
      - MQTT_PASSWORD=password
      - MQTT_TOPIC=printer/commands  # Adjust topic if necessary
      - ADMIN_USER=admin  # Admin user for CUPS
      - ADMIN_PASS=adminpassword  # Admin password for CUPS
    ulimits:
      nofile:  #Set NOFILE limits. 
        soft: 65536
        hard: 65536
    stdin_open: true  # Equivalent to `-it` (interactive terminal)
    tty: true         # Keeps the container running interactively
